#!/usr/bin/env python

import logging

from ukirt2caom2.ingest import IngestRaw

instruments = ('cgs3', 'cgs4', 'ircam', 'michelle', 'ufti', 'uist')

if __name__ == '__main__':
    from argparse import ArgumentParser
    import re

    parser = ArgumentParser()

    parser.add_argument('--instrument', '-i', required=True,
                        choices=instruments)
    parser.add_argument('--date', '-d', required=False,
                        default=None)
    parser.add_argument('--observation', required=False,
                        type=int, default=None)
    parser.add_argument('--dry-run', '-n', required=False,
                        default=False, action='store_true')
    parser.add_argument('--out', required=False,
                        default=None)
    parser.add_argument('--print', dest='dump', required=False,
                        default=False, action='store_true')
    parser.add_argument('--repo', '-r', required=False,
                        default=False, action='store_true')
    parser.add_argument('--verbose', '-v', required=False,
                        default=False, action='store_true')
    parser.add_argument('--control', '-c', required=False,
                        type=str, default=None)

    args = parser.parse_args()

    if args.date is not None and not re.match('^[0-9]{8}$', args.date):
        raise Exception('Invalid date ' + args.date)

    if args.dry_run:
        out_dir = None
        use_repo = False
    else:
        out_dir = args.out
        use_repo = args.repo

        if out_dir is None and not use_repo:
            raise Exception('No output directory specified outside of dry-run mode')

    logging.basicConfig(level=logging.DEBUG if args.verbose else logging.INFO)
    logger = logging.getLogger()

    logger.info('Initializing ingestion')
    raw = IngestRaw()

    logger.info('Staring ingestion')
    num_errors = raw(args.instrument, args.date, args.observation,
                     use_repo, out_dir, args.dump, control_file=args.control)

    logger.info('Finished ingestion')
    print('ukirt2caom2 finished, observations rejected: ' + str(num_errors))
