#!/usr/bin/env python

from __future__ import print_function

import sys

from pymongo import MongoClient

def main(instrument, header, *subheaders):
    mongo = MongoClient()
    collection = mongo.ukirt[instrument]

    results = {}

    for obs in collection.find():
        try:
            key = str(obs['headers'][0][header])
            val = tuple(map(lambda x: str(obs['headers'][0].get(x, '---')),
                            subheaders))

        except KeyError:
            continue

        if key not in results:
            results[key] = set()

        results[key].add(val)

    for key in sorted(results.keys()):
        print('{:10} '.format(key + ':') + ', '.join(
            map(lambda x: '/'.join(x), results[key])))

if __name__ == '__main__':
    if len(sys.argv) < 4:
        print('Usage: ' + sys.argv[0] + ' instrument header subheaders ...')
    else:
        main(sys.argv[1], *sys.argv[2:])
