#!/usr/bin/env python

from ukirt2caom2.ingest import IngestRaw

instruments = ('cgs3', 'cgs4', 'ircam', 'michelle', 'ufti', 'uist')


if __name__ == '__main__':
    from argparse import ArgumentParser
    import re

    parser = ArgumentParser()

    parser.add_argument('--instrument', choices=instruments, required=True)
    parser.add_argument('--date', required=False, default=None)
    parser.add_argument('--observation', type=int, required=False, default=None)

    args = parser.parse_args()

    if args.date is not None and not re.match('^[0-9]{8}$', args.date):
        raise Exception('Invalid date ' + args.date)

    raw = IngestRaw()

    raw(args.instrument, args.date, args.observation)
